name: "smart_irrigation"
type: "python:3.13"

relationships:
  database: "db:postgresql"  # Defines the relationship with the PostgreSQL database

# Configuration for exposing the app to the web
web:
  upstream:
    socket_family: unix  # Specifies socket type
  commands:
    start: "gunicorn -w 4 -b unix:$SOCKET smart_irrigation.wsgi:application"  # Command to start the Gunicorn server
  locations:
    "/":
      passthru: true  # Ensures requests are passed through to the application
    "/static":
      root: "static"  # Specifies the directory for static files
      expires: 1h  # Sets cache expiration for static files
      allow: true  # Allows access to static files

# Persistent disk size for the application in MB
disk: 512

# Local read/write mount for logs
mounts:
  "logs":
    source: local
    source_path: logs  # Directory for logs

# Lifecycle hooks for the application
hooks:
  build: |
    pip install --upgrade pip  # Upgrade pip to the latest version
    pip install -r requirements.txt  # Install required packages
    pip install -r requirements_remote.txt  # Install additional remote requirements
     
    mkdir logs  # Create logs directory
    python manage.py collectstatic --noinput  # Collect static files
    rm -rf logs  # Clean up logs directory

  deploy: |
    python manage.py migrate  # Run database migrations
