# Generated by Django 5.2.4 on 2025-09-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sms_alert_frequency',
        ),
    ]
