# Generated by Django 5.1.6 on 2025-06-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='receive_sms_alerts',
            field=models.BooleanField(default=True, help_text='Designates whether the user wants to receive SMS notifications.', verbose_name='Receive SMS Alerts'),
        ),
    ]
