# Generated by Django 5.0 on 2025-05-22 07:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: +[country code][number], e.g., +1234567890', max_length=20, null=True, validators=[accounts.models.validate_phone_number]),
        ),
    ]
