# Generated by Django 5.2.4 on 2025-09-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_sms_alert',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='quiet_hours_end',
            field=models.TimeField(default='06:00', help_text='End time for quiet hours (no alerts)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='quiet_hours_start',
            field=models.TimeField(default='22:00', help_text='Start time for quiet hours (no alerts)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_alert_frequency',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly'), ('daily', 'Daily')], default='immediate', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_alert_threshold',
            field=models.PositiveIntegerField(default=30, help_text='Moisture level threshold for sending alerts (%)'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['receive_sms_alerts', 'last_sms_alert'], name='accounts_cu_receive_51e455_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone_number'], name='accounts_cu_phone_n_908ea4_idx'),
        ),
    ]
