# Generated by Django 5.1.6 on 2025-06-06 22:31

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_receive_sms_alerts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='api_key',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: +[country code][number]', max_length=20, null=True, validators=[accounts.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='receive_sms_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
