# Generated by Django 5.2.4 on 2025-09-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_customuser_last_sms_alert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_notification_frequency',
            field=models.IntegerField(choices=[(5, '5 seconds'), (10, '10 seconds'), (15, '15 seconds'), (30, '30 seconds'), (45, '45 seconds'), (60, '60 seconds')], default=15, help_text='Frequency for SMS notifications in seconds'),
        ),
    ]
