# Generated by Django 5.2.4 on 2025-09-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_last_notification_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='receive_sms_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
