# Generated by Django 5.2.4 on 2025-09-13 05:55

from django.db import migrations


def disable_sms_for_existing_users(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.update(receive_sms_alerts=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_receive_sms_alerts'),
    ]

    operations = [
        migrations.RunPython(disable_sms_for_existing_users),
    ]
