# Each route describes how an incoming URL will be processed by Platform.sh.
"https://{default}/":
 type: upstream
 upstream: "smart_irrigation:http"
"https://www.{default}/":
 type: redirect
 to: "https://{default}/"

