# Define how incoming URLs are processed

"https://{default}/":
  type: upstream
  upstream: "intelligent_irrigation:http"  # Directs traffic to your application

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"  # Redirects www traffic to the non-www version
