# Generated by Django 5.1.6 on 2025-03-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='threshold',
            field=models.IntegerField(default=50),
        ),
    ]
